title: Kevin 的 Jekyll 博客
description: 自用站点
baseurl: "" # 项目路径（保持空即可）
url: "https://chinakevin588.github.io"

remote_theme: alexander-shvayko/ayer
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "page:num"

# 可选字段
author:
  name: ChinaKevin588
  email: wjk2022kevin@outlook.com
